### ISSUE TITLE
Plugin doesn't compile with vlc 3.0

### ISSUE THREAD

**Issue by astafyev** [BtbN/vlc-htsp-plugin#32]
It seems VLC SDK has changed in 3.0 and I get the following errors:
`g++ -pipe -O2 -Wall -Wextra -std=gnu++0x -I. -g -DMODULE_STRING=\"htsp\" -DVLC_PLUGIN_MAJOR=3 -DVLC_PLUGIN_MINOR=0 -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -DPIC -fPIC -c helper.cpp
helper.cpp:61:49: error: macro "net_Write" passed 5 arguments, but takes just 4
     if(net_Write(obj, sys->netfd, NULL, buf, len) != (ssize_t)len)
                                                 ^
helper.cpp:91:75: error: macro "net_Read" passed 6 arguments, but takes just 4
     if((readSize = net_Read(obj, sys->netfd, NULL, &len, sizeof(len), true)) != sizeof(len))
                                                                           ^
helper.cpp:117:66: error: macro "net_Read" passed 6 arguments, but takes just 4
     if((readSize = net_Read(obj, sys->netfd, NULL, buf, len, true)) != (ssize_t)len)
                                                                  ^
helper.cpp: In function ‘bool TransmitMessageEx(vlc_object_t*, sys_common_t*, HtsMessage)’:
helper.cpp:61:63: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if(net_Write(obj, sys->netfd, NULL, buf, len) != (ssize_t)len)
                                                               ^~~
helper.cpp: In function ‘HtsMessage ReadMessageEx(vlc_object_t*, sys_common_t*)’:
helper.cpp:91:20: error: invalid conversion from ‘ssize_t (*)(vlc_object_t*, int, void*, size_t) {aka long int (*)(vlc_object_t*, int, void*, long unsigned int)}’ to ‘ssize_t {aka long int}’ [-fpermissive]
     if((readSize = net_Read(obj, sys->netfd, NULL, &len, sizeof(len), true)) != sizeof(len))
                    ^~~~~~~~
helper.cpp:117:20: error: invalid conversion from ‘ssize_t (*)(vlc_object_t*, int, void*, size_t) {aka long int (*)(vlc_object_t*, int, void*, long unsigned int)}’ to ‘ssize_t {aka long int}’ [-fpermissive]
     if((readSize = net_Read(obj, sys->netfd, NULL, buf, len, true)) != (ssize_t)len)
                    ^~~~~~~~
Makefile:50: recipe for target 'helper.o' failed
`

**Comment by ThomasLeister** [comment]
Thanks for your hints! I just made the source code ready for VLC 3.0! :-) https://github.com/ThomasLeister/vlc-htsp-plugin

**Comment by meiser79** [comment]
Because of changes in the EPG code, the plugin doesn't compile anymore. Did anyone of you maybe have a look?

**Comment by TRPB** [comment]
take a look here: https://github.com/TomBZombie/vlc-htsp-plugin I've fixed the issues but my knowledge of C isn't good enough to fix some of the other issues
